/**
 * Inlines the page's images so the Worker can serve them.
 *
 * A Worker has no filesystem, so anything it serves has to be part of the code.
 * These are served as their own responses rather than as data URIs in the page
 * because a data URI is a third larger, cannot be cached separately from the
 * markup, and delays first paint by exactly its own size.
 */

import { createHash } from 'node:crypto'
import { readFileSync, readdirSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const here = dirname(fileURLToPath(import.meta.url))
const from = join(here, 'assets')

const files = readdirSync(from).filter((name) => name.endsWith('.png')).sort()

const entries = files.map((name) => {
  const bytes = readFileSync(join(from, name))
  const tag = createHash('sha256').update(bytes).digest('hex').slice(0, 16)
  return { name, tag, base64: bytes.toString('base64'), bytes: bytes.length }
})

const body = entries
  .map(({ name, tag, base64 }) => `  '${name}': { etag: '"${tag}"', base64: '${base64}' },`)
  .join('\n')

writeFileSync(
  join(here, 'src', 'assets.ts'),
  `// Generated by build-assets.mjs from assets/. Do not edit.\n` +
    `export const ASSETS: Record<string, { etag: string; base64: string }> = {\n${body}\n}\n`,
)

const total = entries.reduce((sum, entry) => sum + entry.bytes, 0)
console.log(`${entries.length} assets inlined, ${(total / 1024).toFixed(0)} KB`)
