/**
 * Inlines the widget bundle so the Worker can serve it.
 *
 * A Worker cannot read from disk at runtime, so the bundle has to be part of
 * the code. Generated rather than committed twice: the demo must never serve a
 * different widget from the one this repository builds.
 */

import { readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const here = dirname(fileURLToPath(import.meta.url))
const bundle = readFileSync(join(here, '..', '..', 'public', 'recourse.js'), 'utf8')

writeFileSync(
  join(here, 'src', 'widget.js'),
  `// Generated by build-widget.mjs from public/recourse.js. Do not edit.\nexport const WIDGET = ${JSON.stringify(bundle)}\n`,
)

console.log(`widget inlined, ${(bundle.length / 1024).toFixed(0)} KB`)
